#!/usr/bin/env sh
branch=$(git symbolic-ref --short HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  echo "⛔️ Direct commits to '$branch' are not allowed. Please make a Pull Request."
  exit 1
fi